---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-unseal
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-unseal-role
  namespace: vault
rules:
- apiGroups: [""]
  resources: ["pods/proxy"]
  verbs: ["get", "create"]
  resourceNames: ["https:vault-0:8200", "https:vault-1:8200", "https:vault-2:8200"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-unseal-rolebinding
  namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-unseal-role
subjects:
- namespace: vault
  kind: ServiceAccount
  name: vault-unseal
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal-sa-token
  namespace: vault
  annotations:
    kubernetes.io/service-account.name: vault-unseal
type: kubernetes.io/service-account-token